# -*- coding: utf-8 -*-
"""News_search_summary_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYIL2CIsQvJgneHosnV777wN4yNyFnMD
"""

# streamlit UI

import streamlit as st
from news_search_n_summary_agent import run_news_agent

st.set_page_config(page_title="Dairy News Agent", layout="wide")
st.title("📰 Dairy News Summarizer (SEA)")

st.markdown("Searches dairy-related news for **Thailand, Indonesia, Malaysia, Philippines, Vietnam**, then summarizes and exports Word documents.")

# Date input
start_date = st.date_input("Start date")
end_date = st.date_input("End date")

if start_date and end_date and start_date <= end_date:
    if st.button("🔍 Run News Agent"):
        with st.spinner("Running LangGraph agent... please wait."):
            results = run_news_agent(str(start_date), str(end_date))

        st.success("✅ All summaries generated!")

        for result in results:
            st.subheader(f"{result['country']}")
            st.markdown(result["summary"])
            with open(result["file_path"], "rb") as f:
                st.download_button(
                    label=f"📥 Download {result['country']} Summary",
                    data=f,
                    file_name=result["file_path"].split("/")[-1],
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                )
else:
    st.info("Please select a valid date range.")
